### ISSUE TITLE
how to download  Botnet Dataset by ISCX UNB

### ISSUE THREAD

**Issue by aodiwei** [hmishra2250/BTP#1]
Hi
can you tell me how to donwload  Botnet Dataset by ISCX UNB? i can't find any download link on official website

thx

**Comment by kartik88363** [comment]
You have to mail Prof. Arash Habibi (a.habibi.l@unb.ca), they provide you the access, its not public.

**Comment by aodiwei** [comment]
thx very much, i got the dataset by your advice, but i have a problem, can you help me?
All traces in List of malicious IPs are malicous trace?
for example: we can regard all traces of 147.32.84.180（source ip ) as Neris's trace which is a malicious.
is it right?
Or i should clean non-malicious trace of 147.32.84.180（source ip ) by myself?

**Comment by 5225507** [comment]
Hi dear  aodiwei,
Were you able to label this database?
